# Generated by Django 3.2.6 on 2021-08-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'Types_of_idols',
            },
        ),
        migrations.CreateModel(
            name='Idol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=20)),
                ('pattern', models.CharField(blank=True, max_length=20)),
                ('details', models.CharField(blank=True, max_length=100)),
                ('image1', models.ImageField(upload_to='Images')),
                ('image2', models.ImageField(blank=True, upload_to='Images')),
                ('image3', models.ImageField(blank=True, upload_to='Images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.categories')),
            ],
            options={
                'db_table': 'Idols',
            },
        ),
    ]
