# Generated by Django 3.2.6 on 2021-08-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default=0, upload_to='Images0'),
        ),
        migrations.AlterField(
            model_name='idol',
            name='image1',
            field=models.ImageField(upload_to='Images1'),
        ),
        migrations.AlterField(
            model_name='idol',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Images2'),
        ),
        migrations.AlterField(
            model_name='idol',
            name='image3',
            field=models.ImageField(blank=True, upload_to='Images3'),
        ),
    ]
