# Generated by Django 3.2.6 on 2021-08-12 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_auto_20210811_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='idol',
            name='height',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idol',
            name='model_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
