# Generated by Django 3.2.6 on 2021-08-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_auto_20210812_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(blank=True, default=0, upload_to='Images0'),
        ),
    ]
