# Generated by Django 3.2.6 on 2021-08-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_alter_categories_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idol',
            old_name='pattern',
            new_name='featured',
        ),
    ]
