# Generated by Django 3.2.6 on 2021-08-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0007_alter_categories_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idol',
            old_name='details',
            new_name='price',
        ),
    ]
