# Generated by Django 3.2.6 on 2021-08-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0008_rename_details_idol_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description_min',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
